const dominios= {
    ID_ROL_PACIENTE:"636ac6fe697f26e8f826510d",
    ESTADO_USUARIO_ACTIVO:1,
    ESTADO_USUARIO_INACTIVO:2,
    ESTADO_ROL_ACTIVO: 1,
    ESTADO_ROL_INACTIVO:2,
    ESTADO_AGENDA_CITA_DISPONIBLE:1,
    ESTADO_AGENDA_CITA_NO_DISPONIBLE:2,
    ESTADO_AGENDA_CITA_CANCELADA:3,
    

}

export default dominios